In [1]:
import pandas as pd
import numpy as np
import keras
from keras import layers
from sklearn.metrics import (confusion_matrix, precision_score, auc,
                             roc_curve, recall_score, classification_report, f1_score)
import pickle
import matplotlib.pyplot as plt
from scipy import stats
import tensorflow as tf
import seaborn as sns
from pylab import rcParams
from sklearn.model_selection import train_test_split
from keras.models import Model, load_model
from keras.layers import Input, Dense
from keras.callbacks import ModelCheckpoint, TensorBoard
from keras import regularizers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.losses import sparse_categorical_crossentropy
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import KFold
from sklearn.preprocessing import MinMaxScaler
import random
import scipy.stats as stats
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import csv
from sklearn.cluster import KMeans
from sklearn_som.som import SOM
from sklearn import svm
from sklearn.metrics import auc
from sklearn.metrics import RocCurveDisplay
from sklearn.model_selection import StratifiedKFold
from sklearn import tree
from sklearn.decomposition import PCA

# Dados NSL-KDD

In [2]:
kddtrain = pd.read_csv(r"C:\Users\luang\OneDrive\Documentos\Mestrado\Códigos Python\Autoencoder-based Network Anomaly Detection\KDDTrain.csv")
kddtest = pd.read_csv(r"C:\Users\luang\OneDrive\Documentos\Mestrado\Códigos Python\Autoencoder-based Network Anomaly Detection\KDDTest.csv")

In [3]:
x = pd.concat((kddtrain,kddtest), axis=0)
x = pd.get_dummies(x)
data_class = x['class_anomaly']
data = x.drop(['class_anomaly', 'class_normal'], axis = 1) 

In [4]:
data = data.to_numpy()
data_class = data_class.to_numpy()

# Abordagem Autoencoder-KNN

In [5]:
epochs = 100
batch_size = 256
optimizer = Adam(learning_rate=0.0001)
activation = "relu"
neighbors = 11

num_folds = 10

kfold = StratifiedKFold(n_splits=num_folds, shuffle=True)

fold_no = 1
count = 0

#Métricas ErroRecons
matrix_ErroRecons = np.zeros((num_folds,2,2))
accuracy_ErroRecons = np.zeros(num_folds)
recall_ErroRecons = np.zeros(num_folds)
precision_ErroRecons = np.zeros(num_folds)
f1_ErroRecons = np.zeros(num_folds)

#Métricas KNN
matrix_knn = np.zeros((num_folds,2,2))
accuracy_knn = np.zeros(num_folds)
recall_knn = np.zeros(num_folds)
precision_knn = np.zeros(num_folds)
f1_knn = np.zeros(num_folds)

#Métricas Decision Tree
matrix_dt = np.zeros((num_folds,2,2))
accuracy_dt = np.zeros(num_folds)
recall_dt = np.zeros(num_folds)
precision_dt = np.zeros(num_folds)
f1_dt = np.zeros(num_folds)

#Métricas SVM
matrix_svm = np.zeros((num_folds,2,2))
accuracy_svm = np.zeros(num_folds)
recall_svm = np.zeros(num_folds)
precision_svm = np.zeros(num_folds)
f1_svm = np.zeros(num_folds)

for train, test in kfold.split(data, data_class):
    print("Fold ",fold_no)
    #####################################################
    ####Pré-Processamento
    print("Pré-processando...")
    
    #Separação dos Folds de Treinamento e Teste
    dataTrain = data[train]
    dataTrain_class = data_class[train]
    modelTest = data[test]
    modelTest_class = data_class[test]
    
    #Conta Quantidade de dados
    Train = dataTrain.shape[1]
    noTrain = np.count_nonzero(dataTrain_class == 0)
    anTrain = np.count_nonzero(dataTrain_class == 1)

    #Separa dados normais e anômalos
    normalTrain = dataTrain[np.where(dataTrain_class == 0)]
    anomalyTrain = dataTrain[np.where(dataTrain_class == 1)]
    
    #Divide dados para treinamento
    porcen = 0.50
    j = int(noTrain * porcen)
    
    #Índices escolhidos aleatoriamente
    numbers_knn_normal = np.array(random.sample(range(0, noTrain),j))
    numbers_knn_anomaly = np.array(random.sample(range(0,anTrain),j))
    numbers_autoencoder_normal = np.array(list(set(np.arange(0, noTrain)) - set(numbers_knn_normal)))
    
    #Dados KNN
    knnTrain_normal = normalTrain[numbers_knn_normal]
    knnTrain_anomaly = anomalyTrain[numbers_knn_anomaly]
    knnTrain = np.concatenate((knnTrain_normal, knnTrain_anomaly), axis=0)
    knnTrain_class = np.concatenate((np.zeros(j), np.ones(j)))
    
    #Dados Autoencoder
    autoencoderTrain = normalTrain[numbers_autoencoder_normal]
    autoencoderTrain_class = np.zeros(autoencoderTrain.shape[0])
    
    #Normalização
    scaler = MinMaxScaler()
    scaler.fit(knnTrain)
    autoencoderTrain = scaler.transform(autoencoderTrain)
    knnTrain = scaler.transform(knnTrain)
    modelTest = scaler.transform(modelTest)
    
    #####################################################
    ####PCA
    print("PCA")
    #Modela o PCA
    pca = PCA(n_components=16)
         
    #####################################################
    ####KNN
    ###Treinamento KNN
    print("KNN...")
    pca.fit(autoencoderTrain)
    pca_encoder = pca.transform(knnTrain)
    neigh = KNeighborsClassifier(n_neighbors=neighbors)
    neigh.fit(pca_encoder, knnTrain_class)
    
    #Teste do Modelo
    pca_encoder = pca.transform(modelTest)
    predict_knn = neigh.predict(pca_encoder)
    
    #Métricas
    accuracy_knn[count] = accuracy_score(modelTest_class, predict_knn[:])
    recall_knn[count] = recall_score(modelTest_class, predict_knn[:])
    precision_knn[count] = precision_score(modelTest_class, predict_knn[:])
    f1_knn[count] = f1_score(modelTest_class, predict_knn[:])
    matrix_knn[count] = confusion_matrix(modelTest_class, predict_knn[:])
    print("Finalizado.")
   
    #####################################################
    ####Decision Tree
    ###Treinamento Decision Tree 
    print("DT...")
    pca_encoder = pca.transform(knnTrain)
    dt = tree.DecisionTreeClassifier()
    dt.fit(pca_encoder, knnTrain_class)

    #Teste
    pca_encoder = pca.transform(modelTest)
    predict_dt = dt.predict(pca_encoder)

    #Métricas
    accuracy_dt[count] = accuracy_score(modelTest_class, predict_dt[:])
    recall_dt[count] = recall_score(modelTest_class, predict_dt[:])
    precision_dt[count] = precision_score(modelTest_class, predict_dt[:])
    f1_dt[count] = f1_score(modelTest_class, predict_dt[:])
    matrix_dt[count] = confusion_matrix(modelTest_class, predict_dt[:])
    print("Finalizado.")
    
    #####################################################
    ####SVM
    #Treinamento SVM
    print("SVM...")
    pca_encoder = pca.transform(knnTrain)
    clf = svm.SVC(kernel='rbf')
    clf.fit(pca_encoder, knnTrain_class)
    
    #Teste
    pca_encoder = pca.transform(modelTest)
    predict_svm = clf.predict(pca_encoder)
    
    #Métricas
    accuracy_svm[count] = accuracy_score(modelTest_class, predict_svm[:])
    recall_svm[count] = recall_score(modelTest_class, predict_svm[:])
    precision_svm[count] = precision_score(modelTest_class, predict_svm[:])
    f1_svm[count] = f1_score(modelTest_class, predict_svm[:])
    matrix_svm[count] = confusion_matrix(modelTest_class, predict_svm[:])
    print("Finalizado.")
    
    count = count + 1
    fold_no = fold_no + 1

Fold  1
Pré-processando...
PCA
KNN...
Finalizado.
DT...
Finalizado.
SVM...
Finalizado.
Fold  2
Pré-processando...
PCA
KNN...
Finalizado.
DT...
Finalizado.
SVM...
Finalizado.
Fold  3
Pré-processando...
PCA
KNN...
Finalizado.
DT...
Finalizado.
SVM...
Finalizado.
Fold  4
Pré-processando...
PCA
KNN...
Finalizado.
DT...
Finalizado.
SVM...
Finalizado.
Fold  5
Pré-processando...
PCA
KNN...
Finalizado.
DT...
Finalizado.
SVM...
Finalizado.
Fold  6
Pré-processando...
PCA
KNN...
Finalizado.
DT...
Finalizado.
SVM...
Finalizado.
Fold  7
Pré-processando...
PCA
KNN...
Finalizado.
DT...
Finalizado.
SVM...
Finalizado.
Fold  8
Pré-processando...
PCA
KNN...
Finalizado.
DT...
Finalizado.
SVM...
Finalizado.
Fold  9
Pré-processando...
PCA
KNN...
Finalizado.
DT...
Finalizado.
SVM...
Finalizado.
Fold  10
Pré-processando...
PCA
KNN...
Finalizado.
DT...
Finalizado.
SVM...
Finalizado.


In [6]:
print("Autoencoder - KNN:\n", np.mean(matrix_knn, axis=0), "\nAcurácia: ", np.mean(accuracy_knn), ' +/- ', np.std(accuracy_knn), "\nRecall: ", np.mean(recall_knn), ' +/- ', np.std(recall_knn), "\nPrecision: ", np.mean(precision_knn), ' +/- ', np.std(precision_knn), "\nF1: ", np.mean(f1_knn), ' +/- ', np.std(f1_knn))

print("\nAutoencoder - SVM:\n", np.mean(matrix_svm, axis=0), "\nAcurácia: ", np.mean(accuracy_svm), ' +/- ', np.std(accuracy_svm), "\nRecall: ", np.mean(recall_svm), ' +/- ', np.std(recall_svm), "\nPrecision: ", np.mean(precision_svm), ' +/- ', np.std(precision_svm), "\nF1: ", np.mean(f1_svm), ' +/- ', np.std(f1_svm))

print("\nAutoencoder - Decision Tree:\n", np.mean(matrix_dt, axis=0), "\nAcurácia: ", np.mean(accuracy_dt), ' +/- ', np.std(accuracy_dt), "\nRecall: ", np.mean(recall_dt), ' +/- ', np.std(recall_dt), "\nPrecision: ", np.mean(precision_dt), ' +/- ', np.std(precision_dt), "\nF1: ", np.mean(f1_dt), ' +/- ', np.std(f1_dt))

Autoencoder - KNN:
 [[7582.1  123.3]
 [ 125.  7021.3]] 
Acurácia:  0.9832813774017346  +/-  0.0011366680704497233 
Recall:  0.9825083975783271  +/-  0.001718753067943353 
Precision:  0.9827444346748132  +/-  0.0015217361680789777 
F1:  0.9826251473704153  +/-  0.00118424535828758

Autoencoder - SVM:
 [[7536.   169.4]
 [ 258.5 6887.8]] 
Acurácia:  0.9711885059786718  +/-  0.0014251786576075164 
Recall:  0.9638274360065118  +/-  0.0038583257921932512 
Precision:  0.9760077365286625  +/-  0.0023639771466892516 
F1:  0.9698711439867445  +/-  0.0015364217493661824

Autoencoder - Decision Tree:
 [[7581.9  123.5]
 [ 105.6 7040.7]] 
Acurácia:  0.9845741552550651  +/-  0.0008210661327227428 
Recall:  0.9852231032057942  +/-  0.0014533080487663364 
Precision:  0.9827627211986829  +/-  0.0010370412511083896 
F1:  0.9839905026951559  +/-  0.000856574764019387


In [7]:
Result = np.array(["KNN", "Acurácia", accuracy_knn, np.mean(accuracy_knn), np.std(accuracy_knn),"",
                                "Recall", recall_knn, np.mean(recall_knn), np.std(recall_knn), "",
                                "Precision", precision_knn, np.mean(precision_knn), np.std(precision_knn), "",
                                "F1", f1_knn, np.mean(f1_knn), np.std(f1_knn), "-----------------","-----------------",
                  "Decision Tree",  "Acurácia", accuracy_dt, np.mean(accuracy_dt), np.std(accuracy_dt),"",
                                "Recall", recall_dt, np.mean(recall_dt), np.std(recall_dt), "",
                                "Precision", precision_dt, np.mean(precision_dt), np.std(precision_dt), "",
                                "F1", f1_dt, np.mean(f1_dt), np.std(f1_dt), "-----------------","-----------------",
                  "SVM",  "Acurácia", accuracy_svm, np.mean(accuracy_svm), np.std(accuracy_svm),"",
                                "Recall", recall_svm, np.mean(recall_svm), np.std(recall_svm), "",
                                "Precision", precision_svm, np.mean(precision_svm), np.std(precision_svm), "",
                                "F1", f1_svm, np.mean(f1_svm), np.std(f1_svm), "","",])

np.savetxt('Result_PCA.txt', Result, delimiter = ',',fmt='%s')

C:\Users\luang\anaconda3\envs\keras_env\lib\site-packages\ipykernel_launcher.py:12: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  if sys.path[0] == '':


In [8]:
Result_Matrix = np.array(["KNN", matrix_knn, np.mean(matrix_knn, axis=0), np.std(matrix_knn, axis=0), "-----------------","-----------------",
                          "Decision Tree", matrix_dt, np.mean(matrix_dt, axis=0), np.std(matrix_dt, axis=0), "-----------------","-----------------",
                          "SVM", matrix_svm, np.mean(matrix_svm, axis=0), np.std(matrix_svm, axis=0)])

np.savetxt('Result_PCA_Matrix.txt', Result_Matrix, delimiter = ',',fmt='%s')

C:\Users\luang\anaconda3\envs\keras_env\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  This is separate from the ipykernel package so we can avoid doing imports until
